### PR TITLE
Preserve user choices on tab switch- issue #44

### PR DESCRIPTION
**Pull request by tjayrush**

### CODE REVIEW

**Review by deeayeen — APPROVED** [review]
Perfect!

**Comment by deeayeen** [comment]
Next step could be to preserve open/closed panes such as help and status

**Comment by tjayrush** [comment]
> Next step could be to preserve open/closed panes such as help and status

Yes. Exactly. That's what I'll try to do next.

**Comment by tjayrush** [comment]
Closes issue #44

**Pull request merged**
